
var soaps = [
    { id: "no1", name: "Dióolajos szappan", ingredients: "sheavaj, kókusz olaj, szőlőmag olaj, ricinus olaj, mandula olaj, oliva olaj, lenmag olaj, kakaóvaj", liquid: "diófőzet", fragrance: "mandula illóolaj", others: "", price: 1000, type: "greasy" },
    { id: "no2", name: "Babérleveles szappan", ingredients: "sheavaj, kakaóvaj, kókusz olaj, szőlőmag olaj, ricinus olaj, repceolaj, oliva olaj, lenmag olaj, babérlevél macerátum", liquid: "zöld-fehér tea", fragrance: "széna-mező friss illat", others: "", price: 1200, type: "normal" },
    { id: "no3", name: "Uborkás-avocado-jojoba szappan", ingredients: "sheavaj, kakaóvaj, kókusz olaj, szőlőmagolaj, ricinus olaj, lenmag olaj, napraforgó olaj, oliva olaj, avocado olaj, jojoba olaj", liquid: "uborka szűret, zöld tea, kókusz tej", fragrance: "citromfű olaj", others: "", price: 1100, type: "greasy" },
    { id: "no4", name: "Aloe szappan - argán olajjal", ingredients: "sheavaj, kakaóvaj, kókusz olaj, szőlőmagolaj, ricinus olaj, lenmag olaj, napraforgó olaj, oliva olaj, aloe olaj, argán olaj", liquid: "kókusz tej", fragrance: "cseresznyevirág illat", others: "", price: 1250, type: "dry" },
    { id: "no5", name: "Sárgabarackmag-olajos szappan", ingredients: "shea vaj, kókusz olaj, oliva olaj, ricinus olaj, sárgabarakmag olaj", liquid: "kókusztej", fragrance: "édesnarancs, csokinarancs illat", others: "méz, fahéj, kurkuma", price: 1300, type: "mixed" },
    { id: "no6", name: "Avocado olajos szappan", ingredients: "sheavaj, kakaóvaj, kókusz olaj, szőlőmagolaj, ricinus olaj, lenmag olaj, napraforgó olaj, oliva olaj, avocado olaj, jojoba olaj", liquid: "kamilla és körömvirág tea", fragrance: "rizsvirág illat", others: "", price: 1150, type: "dry" },
    { id: "no7", name: "Kávé szappan - kókusztejjel", ingredients: "sheavaj, kakaóvaj, kókusz olaj,  ricinus olaj, lenmag olaj, napraforgó olaj, oliva olaj", liquid: "kókusztej, kávé főzet", fragrance: "csokinarancs illat", others: "szegfűszeg őrlemény, szegfűszeg macerátum", price: 1250, type: "greasy" },
    { id: "no8", name: "Oliva szappan", ingredients: "oliva olaj, ricinus olaj", liquid: "-", fragrance: "zöldmező illat", others: "babérleveles macerátum", others: "", price: 900, type: "normal" },
    { id: "no9", name: "Himalaya só szappan", ingredients: "sheavaj, kakaóvaj, kókusz olaj, szőlőmagolaj, ricinus olaj,  napraforgó olaj, oliva olaj", liquid: "kókusztej", fragrance: "lime illat", others: "", price: 1050, type: "dry" },
    { id: "no10", name: "Levendula szappan", ingredients: "sheavaj, kakaóvaj, kókusz olaj, szőlőmagolaj, ricinus olaj, lenmag olaj, napraforgó olaj, oliva olaj", liquid: "kecsketej", fragrance: "levendula illat", others: "", price: 1100 },
    { id: "no11", name: "Gránátalmás szappan", ingredients: "sheavaj, kakaóvaj, kókusz olaj, szőlőmagolaj, ricinus olaj, lenmag olaj, napraforgó olaj, oliva olaj, repce olaj, palma olaj", liquid: "gránátalma tea", fragrance: "rizsvirág illat", others: "", price: 1160, type: "dry" },
    { id: "no12", name: "Csipkebogyós szappan", ingredients: "sheavaj, kakaóvaj, kókusz olaj, szőlőmagolaj, ricinus olaj, lenmag olaj, napraforgó olaj, oliva olaj, argan olaj", liquid: "hárs, kamilla tea", fragrance: "hibiszkusz illat", others: "", price: 1400, type: "dry" },
    { id: "no13", name: "Pitypang szappan", ingredients: "Shea vaj, kókusz olaj, kakaóvaj, szőlőmag olaj, lenmag olaj, olíva olaj, avocadó olaj, ricinus olaj, repce olaj", liquid: "körömvirág tea", fragrance: "zöldmező illat", others: "feketeszén, sárgaagyag", price: 1250 },
    { id: "no14", name: "Körömvirág szappan", ingredients: "sheavaj, kakaóvaj, kókusz olaj, repceolaj, ricinus olaj, napraforgó olaj, oliva olaj", liquid: "körömvirág liquid", fragrance: "pro age illat", others: "körömvirág macerátum", price: 1300, type: "mixed" },
    { id: "no15", name: "Jázmin szappan", ingredients: "sheavaj, kakaóvaj, kókusz olaj, ricinus olaj, napraforgó olaj, oliva olaj, argán olaj", liquid: "jázmin liquid", fragrance: "rizsvirág illat", others: "jázmin macerátum, jázmin virágzat", price: 1000, type: "normal" },
    { id: "no16", name: "Feketeribizlis szappan", ingredients: "sheavaj, kakaóvaj, kókusz olaj, szőlőmagolaj, ricinus olaj, lenmag olaj, napraforgó olaj, oliva olaj, repceolaj", liquid: "piros gyümölcstea", fragrance: "magnólia illat", others: "gránátalma macerátum", price: 1090, type: "dry" },
    { id: "no17", name: "Kecsketejes szappan gyógynövényekkel", ingredients: "sheavaj, kókusz olaj, szőlőmagolaj, ricinus olaj, oliva olaj", liquid: "kecsketej", fragrance: "mézes-virág illat", others: "chia mag macerátum,csalán levél őrlemény, kamilla virágzat őrlemény", price: 1450, type: "dry" },
    { id: "no17", name: "Mandula-kókusz szappan", ingredients: "sheavaj, kókusz olaj, szőlőmagolaj, ricinus olaj, oliva olaj", liquid: "kecsketej", fragrance: "mézes-virág illat", others: "chia mag macerátum,csalán levél őrlemény, kamilla virágzat őrlemény", price: 1290, type: "dry" }
];

